# Generated by Django 6.0.1 on 2026-01-22 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storageprovider',
            name='encrypted_credentials',
            field=models.TextField(blank=True, help_text='Encrypted JSON containing provider-specific credentials'),
        ),
    ]
