# Generated by Django 6.0.1 on 2026-01-22 04:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('storage', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_filename', models.CharField(max_length=255)),
                ('file_size', models.BigIntegerField(help_text='File size in bytes')),
                ('content_type', models.CharField(max_length=100)),
                ('storage_path', models.CharField(max_length=512)),
                ('width', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('is_optimized', models.BooleanField(default=False)),
                ('optimized_size', models.BigIntegerField(blank=True, help_text='Optimized file size in bytes', null=True)),
                ('optimization_percentage', models.FloatField(blank=True, help_text='Percentage reduction in size', null=True)),
                ('tags', models.JSONField(blank=True, default=list, help_text='List of tags for categorization')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional image metadata (EXIF, etc.)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('storage_provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='images', to='storage.storageprovider')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='images_imag_user_id_2b12b9_idx'), models.Index(fields=['storage_provider'], name='images_imag_storage_844424_idx')],
            },
        ),
    ]
